# В целом можно так же добавить смену владельца

FROM nginx:stable-alpine3.23-slim

RUN rm -rf /usr/share/nginx/html/*

COPY nginx.conf /etc/nginx/conf.d/default.conf

COPY index.html /usr/share/nginx/html

RUN nginx -t

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
